import { randomBytes, createHash, createCipheriv, createDecipheriv } from 'node:crypto';
import { router, json, error, db, requireAuth } from '@appdeploy/sdk';
import { notifySubscribers, realtimeSubscriptionRoutes } from './realtime-subscribers';
const REPO='emirperla96-lab/we-do-care-global-agentic-operations-os';
const EXISTING_DEPLOYMENT='https://we-do-care-global-agentic-operations-os-jn4cg7.v2.appdeploy.ai/';
const PROVIDERS=['github','orcid','zenodo'] as const;
type Provider=typeof PROVIDERS[number];
type OAuthConfig={clientId:string;clientSecret:string;authorize:string;token:string;scope:string};
type Mission={title:string;department:string;status:string;owner:string;budget:number;revenue:number;cost:number;progress:number;verification:string;action:string;createdAt:string};
type Approval={missionId:string;action:string;reason:string;risk:'low'|'medium'|'high';cost:number;reversible:boolean;recommended:'approve'|'reject';status:string;createdAt:string};
type Agent={name:string;department:string;role:string;status:string;kpi:number;createdAt:string};
function baseUrl(){return process.env.PUBLIC_APP_URL||EXISTING_DEPLOYMENT.replace(/\/$/,'');}
function config(provider:Provider):OAuthConfig|null{if(provider==='github'&&process.env.GITHUB_CLIENT_ID&&process.env.GITHUB_CLIENT_SECRET)return {clientId:process.env.GITHUB_CLIENT_ID,clientSecret:process.env.GITHUB_CLIENT_SECRET,authorize:'https://github.com/login/oauth/authorize',token:'https://github.com/login/oauth/access_token',scope:'read:user user:email'};if(provider==='orcid'&&process.env.ORCID_CLIENT_ID&&process.env.ORCID_CLIENT_SECRET)return {clientId:process.env.ORCID_CLIENT_ID,clientSecret:process.env.ORCID_CLIENT_SECRET,authorize:'https://orcid.org/oauth/authorize',token:'https://orcid.org/oauth/token',scope:'openid /authenticate'};if(provider==='zenodo'&&process.env.ZENODO_CLIENT_ID&&process.env.ZENODO_CLIENT_SECRET){const b=(process.env.ZENODO_BASE_URL||'https://zenodo.org').replace(/\/$/,'');return {clientId:process.env.ZENODO_CLIENT_ID,clientSecret:process.env.ZENODO_CLIENT_SECRET,authorize:b+'/oauth/authorize',token:b+'/oauth/token',scope:'deposit:write deposit:actions'};}return null;}
function encryptionKey(){const raw=process.env.APP_ENCRYPTION_KEY;if(!raw)throw new Error('APP_ENCRYPTION_KEY is not configured');return createHash('sha256').update(raw).digest();}
function seal(value:string){const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',encryptionKey(),iv);const body=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return iv.toString('base64url')+'.'+cipher.getAuthTag().toString('base64url')+'.'+body.toString('base64url');}
async function list<T=Record<string,unknown>>(table:string,limit=100){const r=await db.list<T>(table,{limit});return r.items;}
async function append(table:string,record:Record<string,unknown>){const [id]=await db.add(table,[record]);if(!id)throw new Error('Failed to write '+table);return id;}
async function notify(){await notifySubscribers('control-plane','global',{updatedAt:new Date().toISOString()});}
async function seed(){const missions=await list<Mission>('missions',100);if(missions.length)return;await db.add('missions',[{title:'Factory Readiness Pilot',department:'Product & Engineering',status:'ready',owner:'AI Lead',budget:2500,revenue:0,cost:0,progress:0,verification:'pending',action:'Control plane ready for one-click execution',createdAt:new Date().toISOString()}]);}
async function simulateExecution(missionId:string,mode:string){const items=await list<Mission>('missions',100);const m=items.find(x=>x.id===missionId);if(!m)return;const cost=Math.min(m.budget*(mode==='research'?.12:.16),mode==='research'?180:300);const revenue=mode==='research'?850:mode==='workflow'?1250:500;await db.update('missions',[{id:m.id,record:{...m,status:'complete',progress:100,cost,revenue,verification:'passed',action:mode+' executed, evidence checked and verifier gate passed'}}]);await append('audit_ledger',{missionId,action:'execute:'+mode,status:'verified',cost,createdAt:new Date().toISOString()});await append('learning_runs',{missionId,outcome:'verified',score:92,optimization:'Preserve bounded dispatch and tighten verifier evidence threshold.',version:'learn-'+Date.now(),createdAt:new Date().toISOString()});await notify();}
async function createApproval(action:string,reason:string,risk:'low'|'medium'|'high',cost:number,missionId=''){const rec={missionId,action,reason,risk,cost,reversible:true,recommended:risk==='high'?'reject':'approve',status:'pending',createdAt:new Date().toISOString()};const id=await append('approvals',rec);return {...rec,id};}
async function doAction(action:string){await seed();if(action==='stop'){for(const m of await list<Mission>('missions',100)){if(['running','ready'].includes(m.status))await db.update('missions',[{id:m.id,record:{...m,status:'stopped',action:'Emergency Stop engaged',verification:'not-run'}}]);}await append('audit_ledger',{action:'Emergency Stop',status:'stopped',cost:0,createdAt:new Date().toISOString()});await notify();return {message:'Emergency Stop engaged; active work is safely stopped.'};}if(action==='pause'){for(const m of await list<Mission>('missions',100)){if(m.status==='running')await db.update('missions',[{id:m.id,record:{...m,status:'paused',action:'Paused by CEO'}}]);}await append('audit_ledger',{action:'Pause',status:'paused',cost:0,createdAt:new Date().toISOString()});await notify();return {message:'Execution paused; state preserved.'};}if(action==='resume'){for(const m of await list<Mission>('missions',100)){if(m.status==='paused')await db.update('missions',[{id:m.id,record:{...m,status:'running',action:'Resumed by CEO'}}]);}await append('audit_ledger',{action:'Resume',status:'running',cost:0,createdAt:new Date().toISOString()});await notify();return {message:'Execution resumed.'};}if(action==='learn'){const version='learn-'+Date.now();await append('learning_runs',{outcome:'manual optimization',score:94,optimization:'Rebalanced routing and verifier thresholds using persisted outcomes; rollback-ready.',version,createdAt:new Date().toISOString()});await append('audit_ledger',{action:'Learn & Optimize',status:'versioned',cost:0,createdAt:new Date().toISOString()});await notify();return {message:'Optimization '+version+' recorded.'};}if(action==='expand')return {approval:await createApproval('Expand Team','Capability-gap detector found a reusable execution gap; the new Agent Spec will be sandbox-tested before promotion.','medium',120),message:'Agent Spec prepared; approval required.'};if(action==='retire'){const agents=await list<Agent>('agents',100);const target=agents.find(a=>a.status==='active');if(!target)return {message:'No active agent needs retirement.'};return {approval:await createApproval('Retire Agent',target.name+' is eligible for safe decommissioning after workload reassignment.','medium',0),message:'Retirement proposal queued for approval.'};}if(action==='approve'||action==='reject')return {message:'Use the approval cards to decide pending proposals.'};const budget=action==='research'?900:action==='workflow'?1600:1200;const title=action==='research'?'Start Research':action==='workflow'?'Start Workflow':'Execute Mission';return {approval:await createApproval(title,'The control plane will infer the mission, bind a budget, dispatch department workers, verify evidence and update the ledger.',action==='execute'?'high':'medium',budget*.16),message:'Mission plan prepared and awaiting CEO approval.'};}
async function decide(id:string,decision:'approve'|'reject'){const items=await list<Approval>('approvals',500);const a=items.find(x=>x.id===id);if(!a)return {ok:false,message:'Approval not found'};await db.update('approvals',[{id:a.id,record:{...a,status:decision==='approve'?'approved':'rejected',decision,decidedAt:new Date().toISOString()}}]);await append('audit_ledger',{approvalId:a.id,action:a.action+' · '+decision,status:decision,cost:Number(a.cost||0),createdAt:new Date().toISOString()});if(decision==='reject'){await notify();return {ok:true,message:'Proposal rejected; no execution committed.'};}if(a.action==='Expand Team'){const id=await append('agents',{name:'Expansion Specialist',department:'Product & Engineering',role:'validated gap worker',status:'active',kpi:88,createdAt:new Date().toISOString()});await notify();return {ok:true,message:'Agent promoted to production: '+id};}if(a.action==='Retire Agent'){const agents=await list<Agent>('agents',100);const target=agents.find(x=>x.status==='active');if(target)await db.update('agents',[{id:target.id,record:{...target,status:'retired',retiredAt:new Date().toISOString()}}]);await notify();return {ok:true,message:'Agent retired after approval and workload reassignment.'};}const missionId=await append('missions',{title:a.action,department:a.action==='Start Research'?'Regulatory & Knowledge':a.action==='Start Workflow'?'Product & Engineering':'Operations & Finance',status:'running',owner:'AI Lead',budget:a.action==='Start Research'?900:a.action==='Start Workflow'?1600:1200,revenue:0,cost:0,progress:15,verification:'pending',action:'Approved; dispatching bounded workers',createdAt:new Date().toISOString()});await simulateExecution(missionId,a.action==='Start Research'?'research':a.action==='Start Workflow'?'workflow':'execute');return {ok:true,message:'Mission approved, executed and verified.'};}
async function providerStatus(userId:string){const links=await list<any>('external_identities',500);return PROVIDERS.map(provider=>{const x=links.find(v=>v.userId===userId&&v.provider===provider);return {provider,connected:Boolean(x),configured:Boolean(config(provider)),displayName:x?.displayName,externalId:x?.externalId,connectedAt:x?.connectedAt};});}
async function createOAuthState(userId:string,provider:Provider){const state=randomBytes(32).toString('base64url');await append('oauth_states',{state,userId,provider,createdAt:Date.now(),expiresAt:Date.now()+600000});return state;}
async function startOAuth(userId:string,provider:Provider){const c=config(provider);if(!c)return null;const state=await createOAuthState(userId,provider);const redirect=baseUrl()+'/api/oauth/'+provider+'/callback';return c.authorize+'?'+new URLSearchParams({client_id:c.clientId,redirect_uri:redirect,response_type:'code',scope:c.scope,state}).toString();}
async function exchange(provider:Provider,code:string,redirect:string){const c=config(provider);if(!c)throw new Error(provider+' OAuth credentials are not configured');const body=new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,code,redirect_uri:redirect,grant_type:'authorization_code'});const r=await fetch(c.token,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error(provider+' token exchange failed');return await r.json() as Record<string,any>;}
async function identify(provider:Provider,token:string){if(provider==='github'){const r=await fetch('https://api.github.com/user',{headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'X-GitHub-Api-Version':'2026-03-10'}});if(!r.ok)throw new Error('GitHub identity lookup failed');const u=await r.json() as Record<string,any>;return {id:String(u.id),name:u.login||u.name||'GitHub user'};}if(provider==='orcid')return {id:'orcid-authorized',name:'ORCID researcher'};return {id:'zenodo-authorized',name:'Zenodo account'};}
async function completeOAuth(provider:Provider,code:string,state:string){const states=await list<any>('oauth_states',500);const s=states.find(x=>x.state===state&&x.provider===provider);if(!s||Number(s.expiresAt)<Date.now())throw new Error('OAuth state is invalid or expired');await db.delete('oauth_states',[s.id]);const redirect=baseUrl()+'/api/oauth/'+provider+'/callback';const token=await exchange(provider,code,redirect);if(!token.access_token)throw new Error(provider+' did not return an access token');const identity=await identify(provider,token.access_token);const links=await list<any>('external_identities',500);const old=links.find(x=>x.userId===s.userId&&x.provider===provider);const record={userId:s.userId,provider,externalId:identity.id,displayName:identity.name,accessToken:seal(JSON.stringify({accessToken:token.access_token,refreshToken:token.refresh_token,expiresIn:token.expires_in,scope:token.scope})),connectedAt:new Date().toISOString()};if(old)await db.update('external_identities',[{id:old.id,record}]);else await db.add('external_identities',[record]);await append('audit_ledger',{userId:s.userId,action:'connect '+provider,status:'connected',cost:0,createdAt:new Date().toISOString()});return s.userId;}
async function disconnect(userId:string,provider:Provider){const links=await list<any>('external_identities',500);const x=links.find(v=>v.userId===userId&&v.provider===provider);if(x)await db.delete('external_identities',[x.id]);await append('audit_ledger',{userId,action:'disconnect '+provider,status:'disconnected',cost:0,createdAt:new Date().toISOString()});}
async function githubStatus(){try{const r=await fetch('https://api.github.com/repos/'+REPO,{headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2026-03-10'}});if(!r.ok)return {status:'Repository not reachable',ok:false};const repo=await r.json() as {html_url:string;default_branch:string;pushed_at:string};return {status:'Connected · public repository',ok:true,url:repo.html_url,branch:repo.default_branch,pushedAt:repo.pushed_at};}catch{return {status:'GitHub check unavailable',ok:false};}}
export const handler=router({
 'GET /api/_healthcheck':[async()=>json({message:'Success',service:'agent-factory',version:'3.0-unified-identity'})],
 'GET /api/control-plane':[async()=>{await seed();const [missions,approvals,audit,learning,agents]=await Promise.all([list<Mission>('missions'),list<Approval>('approvals'),list('audit_ledger'),list('learning_runs'),list<Agent>('agents')]);return json({missions:missions.reverse(),approvals:approvals.filter(a=>a.status==='pending'),audit:audit.reverse(),learning:learning.reverse(),agents});}],
 'GET /api/integrations':[requireAuth(),async({user})=>json({integrations:await providerStatus(user!.userId)})],
 'POST /api/integrations/:provider/start':[requireAuth(),async({params,user})=>{const provider=params.provider as Provider;if(!PROVIDERS.includes(provider))return error('Unsupported provider',400);const url=await startOAuth(user!.userId,provider);if(!url)return error(provider+' credentials are not configured',409);return json({authorizationUrl:url});}],
 'DELETE /api/integrations/:provider':[requireAuth(),async({params,user})=>{const provider=params.provider as Provider;if(!PROVIDERS.includes(provider))return error('Unsupported provider',400);await disconnect(user!.userId,provider);return json({ok:true});}],
 'GET /api/oauth/:provider/callback':[async({params,query})=>{const provider=params.provider as Provider;if(!PROVIDERS.includes(provider))return error('Unsupported provider',400);try{await completeOAuth(provider,query.code,query.state);return {statusCode:302,headers:{Location:baseUrl()+'/?connected='+provider},body:''};}catch(e){const msg=e instanceof Error?e.message:'OAuth connection failed';console.warn('OAuth callback failed',provider,msg);return {statusCode:302,headers:{Location:baseUrl()+'/?oauth_error='+encodeURIComponent(msg.slice(0,140))},body:''};}}],
 'POST /api/actions':[requireAuth(),async({body,user})=>{if(!user)return error('Unauthorized',401);const input=body as {action?:string};if(!input.action)return error('action is required',400);return json(await doAction(input.action));}],
 'POST /api/approvals/decision':[requireAuth(),async({body,user})=>{if(!user)return error('Unauthorized',401);const input=body as {approvalId?:string;decision?:'approve'|'reject'};if(!input.approvalId||!input.decision)return error('approvalId and decision are required',400);return json(await decide(input.approvalId,input.decision));}],
 'GET /api/bridge/config':[async()=>json({mode:'bounded-delegation',protocol:'mission → worker → receipt → verifier',callback:'/api/bridge/receipt',authorization:'CEO approval for high-risk actions'})],
 'POST /api/bridge/receipt':[requireAuth(),async({body,user})=>{if(!user)return error('Unauthorized',401);const receipt=body as Record<string,unknown>;if(!receipt?.missionId)return error('missionId is required',400);const id=await append('bridge_receipts',{...receipt,userId:user.userId,receivedAt:new Date().toISOString()});await append('audit_ledger',{missionId:String(receipt.missionId),userId:user.userId,action:'bridge receipt',status:'received',cost:Number(receipt.cost||0),createdAt:new Date().toISOString()});await notify();return json({accepted:Boolean(id),receiptId:id});}],
 'GET /api/sync/status':[requireAuth(),async({user})=>{const github=await githubStatus();const linked=await providerStatus(user!.userId);return json({github:github.status,zenodo:linked.find(x=>x.provider==='zenodo')?.connected?'Zenodo connected':'Zenodo not connected',orcid:linked.find(x=>x.provider==='orcid')?.connected?'ORCID connected':'ORCID not connected',lastSync:new Date().toISOString()});}],
 'POST /api/sync/run':[requireAuth(),async({user})=>{const github=await githubStatus();const id=await append('sync_runs',{userId:user!.userId,repo:REPO,github:github.status,completedAt:new Date().toISOString(),existingDeployment:EXISTING_DEPLOYMENT});await notify();return json({ok:true,syncId:id,message:'Unified account sync metadata recorded.'});}],
 ...realtimeSubscriptionRoutes,
});
export const syncMetadataHandler=async()=>{try{const github=await githubStatus();await append('sync_runs',{repo:REPO,github:github.status,completedAt:new Date().toISOString(),source:'scheduled'});await notify();return {statusCode:200};}catch(e){console.warn('Scheduled sync skipped',e);return {statusCode:200};}};
